name: Building my site

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: getting my code first
        uses: actions/checkout@v4

      - name: installing node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: installing dependencies
        run: npm ci
      - name: installing eslint
        run: npm install -D eslint
      - name: linting code
        run: npm run lint
      - name: building site
        run: npm run build
