name: Building my site
on: push
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: getting my code first
        uses: actions/checkout@v7
      - name: installing node
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
      - name: installing dependencies
        run: npm ci
      - name: building site
        run: npm run build
